---

- name: "SECTION | 4.1.x | Configure a firewall"
  ansible.builtin.import_tasks:
    file: 4.1.x.yml

- name: "SECTION | 4.2.x | Configure FirewallD"
  when: firewall == "firewalld"
  ansible.builtin.import_tasks:
    file: 4.2.x.yml

- name: "SECTION | 4.3.x | Configure nftables"
  when: firewall == "nftables"
  ansible.builtin.import_tasks:
    file: 4.3.x.yml
